# Generated by Django 4.2.23 on 2025-09-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Nascimento"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
            ],
        ),
        migrations.CreateModel(
            name="CareRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caregiver",
                    models.CharField(max_length=120, verbose_name="Cuidador"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("medication", "Medicação"),
                            ("meal", "Alimentação"),
                            ("vital", "Sinais Vitais"),
                            ("activity", "Atividade"),
                            ("sleep", "Sono"),
                            ("bathroom", "Banheiro"),
                            ("other", "Outros"),
                        ],
                        default="medication",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("what", models.CharField(max_length=200, verbose_name="O que")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("date", models.DateField(db_index=True, verbose_name="Data")),
                ("time", models.TimeField(verbose_name="Hora")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="care.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-time"],
            },
        ),
    ]
