# Generated by Django 5.2.5 on 2025-09-03 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0002_carerecord_created_by_patient_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("FAMILY", "Familiar"), ("DOCTOR", "Médico")],
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo de cuidado",
                "verbose_name_plural": "Vínculos de cuidado",
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Relacione aqui o User quando o próprio paciente tem login.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="carerecord",
            index=models.Index(
                fields=["patient", "date"], name="care_carere_patient_dbf45d_idx"
            ),
        ),
        migrations.AddField(
            model_name="carelink",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="care_links",
                to="care.patient",
            ),
        ),
        migrations.AddField(
            model_name="carelink",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="care_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carelink",
            unique_together={("user", "patient", "role")},
        ),
    ]
