# Generated by Django 5.1.3 on 2025-09-04 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0004_alter_patient_notes_alter_patient_user_caregroup_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("relation_to_patient", "SELF")),
                fields=("group",),
                name="unique_self_per_group",
            ),
        ),
    ]
