# Generated by Django 5.1.3 on 2025-09-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0005_groupmembership_unique_self_per_group"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="groupmembership",
            name="unique_self_per_group",
        ),
    ]
