# Generated by Django 5.1.3 on 2025-09-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0006_remove_groupmembership_unique_self_per_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="carerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("done", "Realizada"),
                    ("missed", "Não realizado"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
