# Generated by Django 5.1.3 on 2025-11-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0007_carerecord_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="carerecord",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "Não se repete"),
                    ("daily", "Diariamente"),
                    ("weekly", "Semanalmente"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="carerecord",
            name="repeat_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carerecord",
            name="series_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
