# Generated by Django 5.1.3 on 2025-11-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0008_carerecord_recurrence_carerecord_repeat_until_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carerecord",
            name="series_id",
            field=models.UUIDField(
                blank=True, db_column="series_id", db_index=True, null=True
            ),
        ),
        migrations.RenameField(
            model_name="carerecord",
            old_name="series_id",
            new_name="recurrence_group",
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "Não se repete"),
                    ("daily", "Diariamente"),
                    ("weekly", "Semanalmente"),
                    ("monthly", "Mensalmente"),
                ],
                default="none",
                max_length=16,
            ),
        ),
    ]
