# Generated by Django 5.1.3 on 2025-11-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0011_recordreaction_recordcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carerecord",
            name="type",
            field=models.CharField(
                choices=[
                    ("medication", "Medicação"),
                    ("meal", "Alimentação"),
                    ("vital", "Sinais Vitais"),
                    ("activity", "Atividade"),
                    ("progress", "Evolução/Regressão"),
                    ("sleep", "Sono"),
                    ("bathroom", "Banheiro"),
                    ("other", "Outros"),
                ],
                default="medication",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
