# Generated by Django 5.2.8 on 2025-12-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0012_alter_carerecord_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerecord',
            name='missed_reason',
            field=models.TextField(blank=True, verbose_name='Motivo do não realizado'),
        ),
    ]
