# Generated by Django 4.2.19 on 2026-02-25 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care', '0014_medication_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_records', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a'),
        ),
        migrations.CreateModel(
            name='CareShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('night', 'Noite')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='care.caregroup')),
            ],
            options={
                'ordering': ['date', 'shift'],
                'unique_together': {('group', 'date', 'shift')},
            },
        ),
    ]
