# Generated by Django 4.2.19 on 2026-02-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0015_carerecord_assigned_to_careshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='careshift',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Não se repete'), ('daily', 'Diariamente'), ('weekly', 'Semanalmente'), ('biweekly', 'Quinzenalmente'), ('monthly', 'Mensalmente')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='careshift',
            name='recurrence_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='careshift',
            name='repeat_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careshift',
            name='repeat_weekdays',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
