# Generated by Django 4.2.19 on 2026-03-12 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care', '0016_careshift_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tarefa')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Data')),
                ('done', models.BooleanField(default=False, verbose_name='Feito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='care.caregroup')),
            ],
            options={
                'ordering': ['date', 'order', 'created_at'],
                'indexes': [models.Index(fields=['group', 'date'], name='care_checkl_group_i_3ab235_idx')],
            },
        ),
    ]
