# Generated by Django 4.2.19 on 2026-03-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0017_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='linked_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_item', to='care.carerecord', verbose_name='Registro vinculado'),
        ),
    ]
