# Generated by Django 4.2.19 on 2026-05-04 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care', '0019_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='pushtoken',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Removido por'),
        ),
    ]
