# Generated by Django 5.1.15 on 2026-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0020_push_token_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="carerecord",
            name="notified_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Lembrete enviado em"
            ),
        ),
    ]
