# Generated by Django 5.1.15 on 2026-06-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0020_push_token_soft_delete"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklySummaryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_start",
                    models.DateField(db_index=True, verbose_name="Início da semana"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_summaries",
                        to="care.caregroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de resumo semanal",
                "verbose_name_plural": "Logs de resumo semanal",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "week_start"),
                        name="unique_weekly_summary_per_group",
                    )
                ],
            },
        ),
    ]
