# Generated by Django 5.1.15 on 2026-06-30 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0021_carerecord_notified_at"),
        ("care", "0021_notification"),
    ]

    operations = []
