# Generated by Django 5.1.15 on 2026-06-30 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0022_merge_0021_carerecord_notified_at_0021_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
