# Generated by Django 5.1.15 on 2026-08-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0026_chatconsent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carerecord",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="Hora"),
        ),
    ]
