# Generated by Django 5.1.15 on 2026-08-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0026_chatconsent"),
    ]

    operations = [
        migrations.AddField(
            model_name="carerecord",
            name="missed_notified_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Notificação de não realizado enviada em",
            ),
        ),
    ]
