# Generated by Django 5.1.15 on 2026-08-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0027_carerecord_missed_notified_at"),
        ("care", "0027_carerecord_time_nullable"),
    ]

    operations = []
