# Generated by Django 5.1.15 on 2026-08-09 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0028_merge_20260807_1203"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carerecord",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Removido em"
            ),
        ),
        migrations.AddField(
            model_name="carerecord",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_care_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Removido por",
            ),
        ),
    ]
