# Generated by Django 5.1.15 on 2026-08-10 05:43

import care.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0029_carerecord_deleted_at_carerecord_deleted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="carerecord",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=care.models.care_record_photo_path,
                verbose_name="Foto",
            ),
        ),
    ]
