# Generated by Django 5.1.15 on 2026-08-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0029_carerecord_deleted_at_carerecord_deleted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="receive_weekly_report",
            field=models.BooleanField(
                default=True, verbose_name="Receber relatorio semanal por email"
            ),
        ),
    ]
