# Generated by Django 4.2.19 on 2026-08-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0030_carerecord_photo"),
        ("care", "0031_groupmembership_receive_weekly_report"),
    ]

    operations = []
