# Generated by Django 4.2.19 on 2026-08-10 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("care", "0032_merge_20260810_1430"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="groupmembership",
            name="unique_user_one_group",
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "group"), name="unique_user_group_membership"
            ),
        ),
    ]
