# Generated by Django 5.1.3 on 2025-09-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de nascimento"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=11, null=True, unique=True, verbose_name="CPF"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nome completo"
            ),
        ),
    ]
