# Generated by Django 5.1.15 on 2026-08-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_birth_date_profile_cpf_profile_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="weekly_report_opt_out",
            field=models.BooleanField(
                default=False, verbose_name="Não receber relatório semanal por e-mail"
            ),
        ),
    ]
