"""
Django settings for cuidarjuntos project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis de um arquivo .env (desenvolvimento local). Em produção
# (ex.: PythonAnywhere) as variáveis vêm do ambiente e este passo é no-op.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-2nk(r$728_m!cak*s-*+4+v0aw9nd(o_+r%dc91%tlj-$#4s=$"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "tuzinhorisonho.pythonanywhere.com",
    "localhost",
    "127.0.0.1",
    "testserver",
    "10.42.236.47",  # IP local para aceitar conexões do celular
    "*",  # Permitir qualquer host em desenvolvimento (REMOVER EM PRODUÇÃO!)
]

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "arthur.poggy2005@gmail.com"
# EMAIL_TIMEOUT = 20
EMAIL_HOST_USER = "arthur.poggy2005@gmail.com"
DEFAULT_FROM_EMAIL = f"CuidarJuntos <{EMAIL_HOST_USER}>"
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_SUBJECT_PREFIX = "[CuidarJuntos] "
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24  # 24h (opcional)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "care",
    "accounts",
    # DRF + API
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    "api",
    # Celery
    "django_celery_beat",
    "django_celery_results",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cuidarjuntos.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

TEMPLATES[0]["OPTIONS"]["context_processors"] += [
    "care.context_processors.current_group",
]

WSGI_APPLICATION = "cuidarjuntos.wsgi.application"

CSRF_TRUSTED_ORIGINS = [
    "https://tuzinhorisonho.pythonanywhere.com",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# PythonAnywhere reverse proxy: Django precisa saber que o request é HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Cookies só via HTTPS (produção usa HTTPS exclusivamente)
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (uploads de usuario, ex.: foto anexada a um CareRecord)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'care:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
from datetime import timedelta  # noqa: E402

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "api.pagination.StandardPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_RATES": {
        # Rate limit do endpoint de chat com IA (por usuário autenticado).
        "chat": "20/min",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "CuidarJuntos API",
    "DESCRIPTION": "API REST para o app mobile CuidarJuntos",
    "VERSION": "1.0.0",
}

# ---------------------------------------------------------------------------
# CORS (Expo dev servers)
# ---------------------------------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True  # Desenvolvimento (REMOVER EM PRODUÇÃO!)
CORS_ALLOW_CREDENTIALS = True

# ---------------------------------------------------------------------------
# Celery
# ---------------------------------------------------------------------------
from celery.schedules import crontab  # noqa: E402

CELERY_BROKER_URL = os.environ.get(
    "CELERY_BROKER_URL", os.environ.get("REDIS_URL", "redis://localhost:6379/0")
)

# Se django_celery_results estiver instalado (task 69), usamos "django-db"
# como backend padrão de resultados; senão caímos de volta para o Redis.
try:
    import django_celery_results  # noqa: F401

    _CELERY_RESULT_BACKEND_DEFAULT = "django-db"
    if "django_celery_results" not in INSTALLED_APPS:
        INSTALLED_APPS.append("django_celery_results")
except ImportError:
    _CELERY_RESULT_BACKEND_DEFAULT = os.environ.get(
        "REDIS_URL", "redis://localhost:6379/0"
    )

CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND", _CELERY_RESULT_BACKEND_DEFAULT
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = False  # True em testes via override_settings

# O Celery Beat, por padrão, só lê o dict estático CELERY_BEAT_SCHEDULE abaixo.
# Para que ele também dispare os PeriodicTask criados no banco pelo comando
# `setup_schedules` (django-celery-beat), o scheduler precisa ser trocado para
# o DatabaseScheduler. Sem isso, os PeriodicTask ficam registrados mas nunca
# são executados em produção.
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

CELERY_BEAT_SCHEDULE = {
    "notify-upcoming-records": {
        "task": "api.tasks.notify_upcoming_records",
        "schedule": 30 * 60,  # a cada 30 minutos
    },
    # O resumo semanal por grupo (antes "notify-weekly-summary", segunda às
    # 09h, disparando todos os grupos de uma vez) foi substituído pelo
    # agendamento por grupo via django-celery-beat (PeriodicTask), criado
    # pelo management command `setup_schedules` — segunda-feira às 08h,
    # chamando `api.tasks.send_weekly_report` uma vez por `CareGroup`. Manter
    # os dois ativos faria cada usuário receber duas notificações quase
    # idênticas na mesma semana. A task `notify_weekly_summary` continua no
    # código (com testes) mas não é mais agendada automaticamente aqui.

    # Envia os cuidados PENDING do dia seguinte para o calendário externo
    # dos membros que conectaram um (card #45). 06:00 no fuso do projeto
    # (CELERY_TIMEZONE = TIME_ZONE = America/Sao_Paulo), cedo o bastante
    # para o evento já estar na agenda quando a pessoa acordar.
    "sync-upcoming-to-calendar": {
        "task": "api.tasks.sync_upcoming_to_calendar",
        "schedule": crontab(hour=6, minute=0),
    },
}

# ---------------------------------------------------------------------------
# Anthropic (assistente de IA)
# ---------------------------------------------------------------------------
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
ANTHROPIC_MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-haiku-4-5-20251001")
# Privacidade: o assistente envia dados clínicos do paciente a um provedor
# externo (Anthropic), então fica DESABILITADO por padrão. Só deve ser ligado
# (CHAT_ASSISTANT_ENABLED=1) em ambientes onde já exista consentimento explícito
# dos responsáveis pelo grupo. Sem isso, o endpoint responde 503 amigável.
CHAT_ASSISTANT_ENABLED = os.environ.get("CHAT_ASSISTANT_ENABLED", "0") == "1"

# ---------------------------------------------------------------------------
# Criptografia em repouso (django-cryptography)
# ---------------------------------------------------------------------------
# Usada pelos campos `encrypt(...)` de `care.models.ExternalCalendarToken`
# (tokens OAuth de calendário externo).
#
# Por padrão o django-cryptography deriva a chave do SECRET_KEY. Isso é
# inadequado aqui por dois motivos:
#
# 1. O SECRET_KEY deste projeto está versionado no repositório, então a
#    chave de criptografia seria derivável por qualquer um com acesso ao
#    código -- os tokens estariam cifrados apenas contra um dump do banco.
# 2. O SECRET_KEY precisa poder ser rotacionado. Se a chave de criptografia
#    depender dele, rotacionar torna todos os tokens gravados ilegíveis
#    (InvalidToken na leitura), sem caminho de recuperação.
#
# Por isso a chave é separada e vem do ambiente. Gerar com:
#     python -c "import secrets; print(secrets.token_urlsafe(64))"
#
# Em dev/teste, sem a env var, caímos no SECRET_KEY (comportamento padrão do
# pacote) -- aceitável porque não há token real. Em produção a ausência é
# um erro de configuração: veja a checagem logo abaixo.
CRYPTOGRAPHY_KEY = os.environ.get("CRYPTOGRAPHY_KEY") or None

if not DEBUG and CRYPTOGRAPHY_KEY is None:
    import warnings

    warnings.warn(
        "CRYPTOGRAPHY_KEY não definida: os tokens de calendário externo serão "
        "cifrados com uma chave derivada do SECRET_KEY, que está versionado. "
        "Defina CRYPTOGRAPHY_KEY no ambiente antes de conectar contas reais.",
        RuntimeWarning,
        stacklevel=1,
    )

# ---------------------------------------------------------------------------
# Integração com calendários externos (Google Calendar / Microsoft Outlook)
# ---------------------------------------------------------------------------
# As credenciais reais só existem depois que os apps OAuth forem cadastrados
# no Google Cloud Console e no Azure/Entra (fora do escopo de código). Em
# dev/teste ficam vazias/fake e as chamadas às APIs são sempre mockadas nos
# testes automatizados -- nunca chamamos a API real do Google/Microsoft.
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET", "")
GOOGLE_CALENDAR_REDIRECT_URI = os.environ.get(
    "GOOGLE_CALENDAR_REDIRECT_URI",
    "http://localhost:8000/api/v1/calendar/google/callback/",
)

MICROSOFT_CLIENT_ID = os.environ.get("MICROSOFT_CLIENT_ID", "")
MICROSOFT_CLIENT_SECRET = os.environ.get("MICROSOFT_CLIENT_SECRET", "")
MICROSOFT_TENANT_ID = os.environ.get("MICROSOFT_TENANT_ID", "common")
MICROSOFT_REDIRECT_URI = os.environ.get(
    "MICROSOFT_REDIRECT_URI",
    "http://localhost:8000/api/v1/calendar/microsoft/callback/",
)

# Deep link do app (Expo) para onde o navegador é redirecionado ao fim do
# fluxo OAuth. A view de callback sempre anexa uma querystring dizendo o que
# aconteceu (?connected=<provider> no sucesso, ?error=<motivo> na falha), em
# vez de usar deep links separados -- assim o app tem um único ponto de
# entrada e consegue diferenciar os motivos de erro para o usuário.
CALENDAR_INTEGRATION_DEEP_LINK = os.environ.get(
    "CALENDAR_INTEGRATION_DEEP_LINK", "cuidarjuntos://integrations"
)

# Quanto do CareRecord vai para o calendario externo (card #46).
#
# "discreet" (default): o evento leva so o horario e um titulo generico
# ("[CuidarJuntos] Cuidado agendado"). "full" inclui o `what` e a
# `description` -- ou seja, dados de saude do paciente saem para servidores
# do Google/Microsoft, sob a conta pessoal do cuidador. Isso e transferencia
# a terceiro e exige consentimento explicito e informado, no mesmo molde do
# ChatConsent que ja existe no projeto; enquanto esse consentimento nao for
# implementado, o default conservador e o unico seguro.
CALENDAR_EVENT_DETAIL_LEVEL = os.environ.get(
    "CALENDAR_EVENT_DETAIL_LEVEL", "discreet"
)
